### ISSUE TITLE
ZYN golbal setting screen 

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#299]
Pressing the ZYN icon at the top left of the screen twice brings up the global settings window.
All the labels are on top of one another in the same place at the top of the window above the title "GLOBAL SETTINGS".
I'm using Manjaro linux on amd processor.
This problem was there before the recent updates of the past few days.

**Comment by fundamental** [comment]
Fixed via ca347aa1112d5e521d1f3bed62b871a28a3d26aa

**Comment by zynmuse** [comment]
what does
Fixed via ca347aa1112d5e521d1f3bed62b871a28a3d26aa
mean?

**Comment by fundamental** [comment]
It means my copy/paste wasn't working right 
https://github.com/mruby-zest/mruby-zest-build/commit/5be75d8be78dde67d7e9c7f5f927ddd96c22ebee is the commit I meant to reference.

**Comment by zynmuse** [comment]
Thank you for the correction.
Today I did a complete delete and then git clone of the master.
Rebuilt everything, and I still have this same problem.
I only run the standalone executables  which my launch scripts call the complete path :
..../master/build/zyn-fusion-linux-64bit-3.0.6-git-release/zyn-fusion
..../master/build/zyn-fusion-linux-64bit-3.0.6-git-release/zynaddsubfx

Labels in Global Settings still all at the top of the window. 

Note these all cloned and rebuilt today and are dated today and the time I built them.

**Comment by fundamental** [comment]
![zyn-settings](https://user-images.githubusercontent.com/766621/132232956-532c9d61-b532-4e72-9dcf-8e8b458fdc98.png)
^^ is what I'm seeing on my end. It still looks quite clunky, but it no longer has the described bug after the modification to Forms.qml. It's possible that getting OSC values back is triggering some sort of re-layout, but I had no real reason to suspect that given the implementation.

**Comment by zynmuse** [comment]
![ZunFuxion-Global-Settings](https://user-images.githubusercontent.com/63783478/132243316-951265ef-b5ae-4bd4-ae3d-0c6716804d3b.png)

This is what I am getting. Just running zyn-fusion without zynaddsubfx - no osc messages anywhere still gives me this display.

**Comment by fundamental** [comment]
Mind cloning mruby-zest-build, running make, and make run? I don't see how we would be getting inconsistent results.

**Comment by zynmuse** [comment]
OK
So if I run the Makefile in 
.....master/src/mruby-zest-build/
Then I run the executable in that same folder called "Zest" I get the correct layout.
Also running
/master/build/zyn-fusion-linux-64bit-3.0.6-git-release/zyn-fusion is now fixed.

It would appear that running the Makefile has fixed the problem,  maybe suggesting a build problem in the higher level makefile?

**Comment by fundamental** [comment]
Strange. I'll make a mental note of that, though running make should invoke a ruby script to regenerate all of the translated .qml code which mruby then compiles into bytecode. I haven't seen make fail to pick something up, but if it happens again it will be confirmed to be a possible build system issue.

**Comment by zynmuse** [comment]
Actually ignore that for a while. I'm still able to get the bad version when I run it via a script. The problem could be mine or my system!

**Comment by zynmuse** [comment]
OK. This was my problem after all. It was fixed by making the working directory the same as the exec directory.

**Comment by fundamental** [comment]
No problem. That sort of mixup is easy to have happen.

**Comment by zynmuse** [comment]
Thanks. You're so kind.
